language: node_js
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
after_install:
    - node_modules/.bin/lerna bootstrap
node_js:
  - "lts/*"
  - "node"
  - 6
  - 7
  - 8
  - 9
  - 10
after_success:
  - nyc report --reporter=lcov
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT